pretrained_model_path: checkpoints/stable-diffusion-v1-4
output_dir: tune_a_video_model/birds-standing
train_data:
  video_path: data/birds-standing.mp4
  prompt: Three birds are standing on a wall.
  height: 448
  width: 768
  n_sample_frames: 16
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - A cat, a rabbit, and a chicken are standing on a wall, with the cat on the left, the rabbit in the middle and the chicken on the right.
  video_length: 16
  height: 448
  width: 768
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 200
checkpointing_steps: 1000
validation_steps: 200
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
