pretrained_model_path: checkpoints/stable-diffusion-v1-4
output_dir: tune_a_video_model/hares-grazing
train_data:
  video_path: data/hares-grazing.mp4
  prompt: Two hares are grazing in the grass.
  height: 448
  width: 768
  n_sample_frames: 16
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - A cat and a swan are grazing in the grass, with the cat is to the left of the swan.
  video_length: 16
  height: 448
  width: 768
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 200
checkpointing_steps: 1000
validation_steps: 200
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
